# Generated by Django 5.1.7 on 2025-04-01 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Schedule Invitation', 'Schedule Invitation'), ('Permutation Request', 'Permutation Request'), ('Permutation Response', 'Permutation Response'), ('Schedule Update', 'Schedule Update'), ('Appointment Alarm', 'Alarm'), ('System Notification', 'System')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actions', models.JSONField(blank=True, default=dict)),
                ('delieved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledAlarm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minutes_before', models.PositiveIntegerField()),
                ('scheduled_time', models.DateTimeField()),
                ('triggered', models.BooleanField(default=False)),
            ],
        ),
    ]
