# Generated by Django 5.1.7 on 2025-04-01 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledalarm',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_alarms', to='schedule.timeslot'),
        ),
        migrations.AddField(
            model_name='scheduledalarm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_alarms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='notificatio_user_id_8944a4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='notificatio_type_94f703_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_f70e89_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_fcd7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledalarm',
            index=models.Index(fields=['user'], name='notificatio_user_id_a31dda_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledalarm',
            index=models.Index(fields=['scheduled_time'], name='notificatio_schedul_d251dc_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledalarm',
            index=models.Index(fields=['triggered'], name='notificatio_trigger_206531_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledalarm',
            unique_together={('user', 'time_slot', 'minutes_before')},
        ),
    ]
