# Generated by Django 5.1.7 on 2025-04-01 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permutationrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_permutations', to='schedule.participant'),
        ),
        migrations.AddField(
            model_name='permutationrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_permutations', to='schedule.participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='schedule.role'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='participant',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='time_slots', to='schedule.participant'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='schedule_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='schedule.scheduleday'),
        ),
        migrations.AddField(
            model_name='permutationrequest',
            name='recipient_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_permutation_requests', to='schedule.timeslot'),
        ),
        migrations.AddField(
            model_name='permutationrequest',
            name='requester_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_permutation_requests', to='schedule.timeslot'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['owner'], name='schedule_sc_owner_i_4f450c_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['created_at'], name='schedule_sc_created_bada1d_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_complete'], name='schedule_sc_is_comp_f93a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['schedule'], name='schedule_ro_schedul_96ea4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('schedule', 'name')},
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['schedule'], name='schedule_pa_schedul_4a5e80_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user'], name='schedule_pa_user_id_c2e4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['invitation_accepted'], name='schedule_pa_invitat_52d371_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('schedule', 'user')},
        ),
        migrations.AddIndex(
            model_name='scheduleday',
            index=models.Index(fields=['schedule', 'date'], name='schedule_sc_schedul_38faf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleday',
            unique_together={('schedule', 'date')},
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['schedule_day'], name='schedule_ti_schedul_9a9b04_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['is_available'], name='schedule_ti_is_avai_012bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['sync_status'], name='schedule_ti_sync_st_da1154_idx'),
        ),
        migrations.AddIndex(
            model_name='permutationrequest',
            index=models.Index(fields=['requester'], name='schedule_pe_request_185c74_idx'),
        ),
        migrations.AddIndex(
            model_name='permutationrequest',
            index=models.Index(fields=['recipient'], name='schedule_pe_recipie_061752_idx'),
        ),
        migrations.AddIndex(
            model_name='permutationrequest',
            index=models.Index(fields=['status'], name='schedule_pe_status_b90e69_idx'),
        ),
        migrations.AddIndex(
            model_name='permutationrequest',
            index=models.Index(fields=['created_at'], name='schedule_pe_created_1bd13f_idx'),
        ),
    ]
