# Generated by Django 5.1.7 on 2025-04-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='min_days_selection',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum number of days each participant must select', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user_specific_min_days',
            field=models.JSONField(default=dict, help_text='User-specific minimum days requirements {user_id: min_days}'),
        ),
    ]
